version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
    command: npm run dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://admin:password@db:5432/btird
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d btird"]
      interval: 5s
      timeout: 3s
      retries: 5

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: btird
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "btird"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata_dev:
