version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "0.0.0.0:5174:80"
    depends_on:
      - backend
    # restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "0.0.0.0:8001:8000"
    environment:
      - DATABASE_URL=postgresql://admin:password@db:5432/btird
    depends_on:
      db:
        condition: service_healthy
    # restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

  db:
    image: postgres:15
    # restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: btird
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "btird"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata_prod:
