name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy to server
      run: |
        scp -r . user@yourserver:/opt/app
        ssh user@yourserver 'cd /opt/app && ./scripts/deploy.sh'
